name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with local tag
        run: |
          docker build -t snipeit-build .

      - name: Tag image for DockerHub
        run: |
          docker tag snipeit-build toandn2205/snipeit:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push toandn2205/snipeit:latest
